spring:
  application:
    name: instagram-backend

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:instagram
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 80